### ISSUE TITLE
why are you using those rewrite rules and not the paths directly?

### ISSUE THREAD

**Issue by aguaviva** [cubny/lite-reader#8]
Just wondering. I am using nginx and it doesnt support the rewrite rules file from apache. i thought about renaming directories. Before doing that I wanted to understand why you decided to go for using rewrite and not any other solution (like renaming dirs).

I cant wait to use lite-reader!! :))

**Comment by cubny** [comment]
Have a look at this:
https://github.com/cubny/lite-reader/wiki/Deploying-with-Nginx
